### ISSUE TITLE
Move sources for web to another repository

### ISSUE THREAD

**Issue by sea-kg** [tusur-coex/coex#1]
1. Create new repository tusur-coex/coex-www
2. move sources to repository tusur-coex/coex-www

**Comment by sea-kg** [comment]
"Move" - it's mean remove from old place. Not just copy.. )

**Comment by IgorPolyakov** [comment]
commit in "develop" branch. When we merge it, folder "www" will be removed from master branch.

**Comment by sea-kg** [comment]
OK. Sorry...

**Comment by mrB4el** [comment]
done
